### ISSUE TITLE
Chnage heading container height.

### ISSUE THREAD

**Issue by Pradumnasaraf** [Pradumnasaraf/Pradumnasaraf.github.io#13]
### Description

Change the height of the `heading` container from **600px to 100vh**

### Screenshots

![Screenshot from 2022-02-25 17-14-01](https://user-images.githubusercontent.com/51878265/155709785-088dad16-c0ae-44fd-acf6-3ac3fe5903a1.png)

**Comment by Atharv-777** [comment]
Shall i do it?

**Comment by Pradumnasaraf** [comment]
> Shall i do it?

Yes, go ahead. Thank you for your interest

**Comment by Pradumnasaraf** [comment]
#14
