### ISSUE TITLE
[OTHER] Not mobile responsive 

### ISSUE THREAD

**Issue by E-fais** [Pradumnasaraf/Pradumnasaraf.github.io#20]
### What would you like to share?

Not looking good on mobile device.
I would like to work on this issue. 
![2833982F-6757-4373-BCB0-AD9145E0E3F0](https://user-images.githubusercontent.com/102040088/195036486-cca4a401-e901-4041-a26a-e15b0a7f7177.png)

**Comment by Pradumnasaraf** [comment]
Thank you for opening the issue, go ahead. 

Just a small question, are you going to fix it for other pages as well apart from the Homepage?

**Comment by E-fais** [comment]
> Thank you for opening the issue, go ahead.
> 
> Just a small question, are you going to fix other pages as well apart from the Homepage?
I would like to work on the Home Page for the time being ;)

**Comment by E-fais** [comment]
> Thank you for opening the issue, go ahead.
> 
> Just a small question, are you going to fix other pages as well apart from the Homepage?

I would like to work on the Home Page for the time being ;)

**Comment by Pradumnasaraf** [comment]
> > Thank you for opening the issue, go ahead.
> > Just a small question, are you going to fix other pages as well apart from the Homepage?
> 
> I would like to work on the Home Page for the time being ;)

Awesome go ahead
