### ISSUE TITLE
feat: hover effects in the navbar

### ISSUE THREAD

**Issue by mnik7044** [Pradumnasaraf/Pradumnasaraf.github.io#27]
### Description

The footers and other icons have a hover effect, except the navbar I want to add the hover effect to increase the interactiveness of the website.

**Comment by mnik7044** [comment]
Hey @Pradumnasaraf I want to add the hover effect in the navbar of the website to increase the interactiveness of the website please assign this issue to me

**Comment by Pradumnasaraf** [comment]
> Hey @Pradumnasaraf I want to add the hover effect in the navbar of the website to increase the interactiveness of the website please assign this issue to me

Hey, go ahead.

**Comment by Pradumnasaraf** [comment]
@mnik7044 you can find some other issues. Thank you

**Comment by mnik7044** [comment]
I will for sure.
