### ISSUE TITLE
[OTHER] Blur background image.

### ISSUE THREAD

**Issue by KendallDoesCoding** [Pradumnasaraf/Pradumnasaraf.github.io#8]
### What would you like to share?

The image on the site is great, but can be blured to look a little more professional

Here's what I got, little issues with the hair after I blured the thing off, trying to resolve shortly
![blu-background (1)](https://user-images.githubusercontent.com/84712013/155149054-cf459c2e-c3af-4ee4-a1a5-a82bfa01ee8b.jpg)

**Comment by Pradumnasaraf** [comment]
Thank you for your suggestion and effort, I will soon replace this image, with some other image :)
