### ISSUE TITLE
[FEATURE] About me section

### ISSUE THREAD

**Issue by KendallDoesCoding** [Pradumnasaraf/Pradumnasaraf.github.io#9]
### Description

About me section on portfolio

### Screenshots

@Pradumnasaraf I can work on this just give me a bit of info about yourself and your coding journey :)

**Comment by Pradumnasaraf** [comment]
> ### Description
> About me section on portfolio
> 
> ### Screenshots
> @Pradumnasaraf I can work on this just give me a bit of info about yourself and your coding journey :)

Thanks for showing your interest, can you please explain in which you will add it and looks (if available), no need to hurry to take your time :)

Again Thank you for opening the issue

**Comment by KendallDoesCoding** [comment]
You can have a look at the second section in my site
https://kendalldoescoding.gq
<https://signal3domain.com/click?redirect=https%3A%2F%2Fkendalldoescoding.gq&dID=1645541012257&linkName=https://kendalldoescoding.gq>...
Let me know if you want a separate page on the website or just in the
second section and will get to work.

**Comment by KendallDoesCoding** [comment]
Thanks. Will start working on it once you give me the details and will
make a PR.

**Comment by KendallDoesCoding** [comment]
@Pradumnasaraf Please provide the info.
